<?php

// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.29 by WSRD Tencent.
// Generated from `ldacc.jce'
// **********************************************************************


require_once('jce.php');

class AuthInfo extends c_struct
{
    public $type;
    public $token;

    public function __clone()
    {
        $this->type = clone $this->type;
        $this->token = clone $this->token;
    }

    public function __construct()
    {
        $this->type = new  c_char;
        $this->token = new  c_string;
    }

    public function get_class_name()
    {
        return "LDACC.AuthInfo";
    }

    public function write(&$_out,$tag)
    {
        jce_header::_pack_header($_out,'c_struct_begin',$tag);
        $this->type->write($_out,0);
        $this->token->write($_out,1);
        jce_header::_pack_header($_out,'c_struct_end',0);
    }
    public function read(&$_in,$tag,$isRequire = true)
    {
        jce_header::_check_struct($_in,$type,$tag,$isRequire);
        jce_header::_unpack_header($_in,$type,$this_tag);
        $this->type->read($_in , 0, true);
        $this->token->read($_in , 1, true);
        $this->_skip_struct($_in);
    }
}

class AccHead extends c_struct
{
    public $gid;
    public $uid;
    public $sequence;
    public $flag;
    public $devtype;
    public $cmd;

    public function __clone()
    {
        $this->gid = clone $this->gid;
        $this->uid = clone $this->uid;
        $this->sequence = clone $this->sequence;
        $this->flag = clone $this->flag;
        $this->devtype = clone $this->devtype;
        $this->cmd = clone $this->cmd;
    }

    public function __construct()
    {
        $this->gid = new  c_int;
        $this->uid = new  c_int64;
        $this->sequence = new  c_int;
        $this->flag = new  c_int;
        $this->devtype = new  c_int;
        $this->cmd = new  c_string;
    }

    public function get_class_name()
    {
        return "LDACC.AccHead";
    }

    public function write(&$_out,$tag)
    {
        jce_header::_pack_header($_out,'c_struct_begin',$tag);
        $this->gid->write($_out,0);
        $this->uid->write($_out,1);
        $this->sequence->write($_out,2);
        $this->flag->write($_out,3);
        $this->devtype->write($_out,4);
        $this->cmd->write($_out,5);
        jce_header::_pack_header($_out,'c_struct_end',0);
    }
    public function read(&$_in,$tag,$isRequire = true)
    {
        jce_header::_check_struct($_in,$type,$tag,$isRequire);
        jce_header::_unpack_header($_in,$type,$this_tag);
        $this->gid->read($_in , 0, true);
        $this->uid->read($_in , 1, true);
        $this->sequence->read($_in , 2, true);
        $this->flag->read($_in , 3, true);
        $this->devtype->read($_in , 4, true);
        $this->cmd->read($_in , 5, true);
        $this->_skip_struct($_in);
    }
}

class AccReq extends c_struct
{
    public $head;
    public $auth_info;
    public $busi_data;
    public $sys_cmd;

    public function __clone()
    {
        $this->head = clone $this->head;
        $this->auth_info = clone $this->auth_info;
        $this->busi_data = clone $this->busi_data;
        $this->sys_cmd = clone $this->sys_cmd;
    }

    public function __construct()
    {
        $this->head = new  AccHead;
        $this->auth_info = new  AuthInfo;
        $this->busi_data = new  c_vector (new c_char);
        $this->sys_cmd = new  c_short;
    }

    public function get_class_name()
    {
        return "LDACC.AccReq";
    }

    public function write(&$_out,$tag)
    {
        jce_header::_pack_header($_out,'c_struct_begin',$tag);
        $this->head->write($_out,0);
        $this->auth_info->write($_out,1);
        $this->busi_data->write($_out,2);
        $this->sys_cmd->write($_out,3);
        jce_header::_pack_header($_out,'c_struct_end',0);
    }
    public function read(&$_in,$tag,$isRequire = true)
    {
        jce_header::_check_struct($_in,$type,$tag,$isRequire);
        jce_header::_unpack_header($_in,$type,$this_tag);
        $this->head->read($_in , 0, true);
        $this->auth_info->read($_in , 1, false);
        $this->busi_data->read($_in , 2, true);
        $this->sys_cmd->read($_in , 3, false);
        $this->_skip_struct($_in);
    }
}

class AccRsp extends c_struct
{
    public $head;
    public $ret_code;
    public $busi_data;
    public $push_msg;
    public $pusher;

    public function __clone()
    {
        $this->head = clone $this->head;
        $this->ret_code = clone $this->ret_code;
        $this->busi_data = clone $this->busi_data;
        $this->push_msg = clone $this->push_msg;
        $this->pusher = clone $this->pusher;
    }

    public function __construct()
    {
        $this->head = new  AccHead;
        $this->ret_code = new  c_int;
        $this->busi_data = new  c_vector (new c_char);
        $this->push_msg = new  c_char;
        $this->pusher = new  c_int64;
    }

    public function get_class_name()
    {
        return "LDACC.AccRsp";
    }

    public function write(&$_out,$tag)
    {
        jce_header::_pack_header($_out,'c_struct_begin',$tag);
        $this->head->write($_out,0);
        $this->ret_code->write($_out,1);
        $this->busi_data->write($_out,2);
        $this->push_msg->write($_out,3);
        $this->pusher->write($_out,4);
        jce_header::_pack_header($_out,'c_struct_end',0);
    }
    public function read(&$_in,$tag,$isRequire = true)
    {
        jce_header::_check_struct($_in,$type,$tag,$isRequire);
        jce_header::_unpack_header($_in,$type,$this_tag);
        $this->head->read($_in , 0, true);
        $this->ret_code->read($_in , 1, true);
        $this->busi_data->read($_in , 2, true);
        $this->push_msg->read($_in , 3, false);
        $this->pusher->read($_in , 4, false);
        $this->_skip_struct($_in);
    }
}

class LoginByOauth1Info extends c_struct
{
    public $appkey;
    public $game_type;
    public $oauth_param;

    public function __clone()
    {
        $this->appkey = clone $this->appkey;
        $this->game_type = clone $this->game_type;
        $this->oauth_param = clone $this->oauth_param;
    }

    public function __construct()
    {
        $this->appkey = new  c_string;
        $this->game_type = new  c_int;
        $this->oauth_param = new  c_map (new c_string,new c_string);
    }

    public function get_class_name()
    {
        return "LDACC.LoginByOauth1Info";
    }

    public function write(&$_out,$tag)
    {
        jce_header::_pack_header($_out,'c_struct_begin',$tag);
        $this->appkey->write($_out,0);
        $this->game_type->write($_out,1);
        $this->oauth_param->write($_out,2);
        jce_header::_pack_header($_out,'c_struct_end',0);
    }
    public function read(&$_in,$tag,$isRequire = true)
    {
        jce_header::_check_struct($_in,$type,$tag,$isRequire);
        jce_header::_unpack_header($_in,$type,$this_tag);
        $this->appkey->read($_in , 0, true);
        $this->game_type->read($_in , 1, true);
        $this->oauth_param->read($_in , 2, true);
        $this->_skip_struct($_in);
    }
}

class LoginByOauth1Rsp extends c_struct
{
    public $tcp_token;
    public $encryptKey;

    public function __clone()
    {
        $this->tcp_token = clone $this->tcp_token;
        $this->encryptKey = clone $this->encryptKey;
    }

    public function __construct()
    {
        $this->tcp_token = new  c_string;
        $this->encryptKey = new  c_string;
    }

    public function get_class_name()
    {
        return "LDACC.LoginByOauth1Rsp";
    }

    public function write(&$_out,$tag)
    {
        jce_header::_pack_header($_out,'c_struct_begin',$tag);
        $this->tcp_token->write($_out,0);
        $this->encryptKey->write($_out,1);
        jce_header::_pack_header($_out,'c_struct_end',0);
    }
    public function read(&$_in,$tag,$isRequire = true)
    {
        jce_header::_check_struct($_in,$type,$tag,$isRequire);
        jce_header::_unpack_header($_in,$type,$this_tag);
        $this->tcp_token->read($_in , 0, true);
        $this->encryptKey->read($_in , 1, true);
        $this->_skip_struct($_in);
    }
}


?>
