// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.29 by WSRD Tencent.
// Generated from `chat.jce'
// **********************************************************************

package ld.Bu;

public final class MsgInfoHolder
{
    public MsgInfoHolder()
    {
    }
    public MsgInfoHolder(MsgInfo value)
    {
        this.value = value;
    }

    public MsgInfo value;
}
