// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.29 by WSRD Tencent.
// Generated from `chat.jce'
// **********************************************************************

package ld.Bu;

public final class MsgInfo extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "Bu.MsgInfo";
    }

    public String fullClassName()
    {
        return "ld.Bu.MsgInfo";
    }

    public int type = 0;

    public int sub_type = 0;

    public long receiver = 0;

    public byte [] content = null;

    public String avatar = "";

    public byte [] nickname = null;

    public short gender = 0;

    public long time = 0;

    public byte [] busi_ext = null;

    public int getType()
    {
        return type;
    }

    public void  setType(int type)
    {
        this.type = type;
    }

    public int getSub_type()
    {
        return sub_type;
    }

    public void  setSub_type(int sub_type)
    {
        this.sub_type = sub_type;
    }

    public long getReceiver()
    {
        return receiver;
    }

    public void  setReceiver(long receiver)
    {
        this.receiver = receiver;
    }

    public byte [] getContent()
    {
        return content;
    }

    public void  setContent(byte [] content)
    {
        this.content = content;
    }

    public String getAvatar()
    {
        return avatar;
    }

    public void  setAvatar(String avatar)
    {
        this.avatar = avatar;
    }

    public byte [] getNickname()
    {
        return nickname;
    }

    public void  setNickname(byte [] nickname)
    {
        this.nickname = nickname;
    }

    public short getGender()
    {
        return gender;
    }

    public void  setGender(short gender)
    {
        this.gender = gender;
    }

    public long getTime()
    {
        return time;
    }

    public void  setTime(long time)
    {
        this.time = time;
    }

    public byte [] getBusi_ext()
    {
        return busi_ext;
    }

    public void  setBusi_ext(byte [] busi_ext)
    {
        this.busi_ext = busi_ext;
    }

    public MsgInfo()
    {
        setType(type);
        setSub_type(sub_type);
        setReceiver(receiver);
        setContent(content);
        setAvatar(avatar);
        setNickname(nickname);
        setGender(gender);
        setTime(time);
        setBusi_ext(busi_ext);
    }

    public MsgInfo(int type, int sub_type, long receiver, byte [] content, String avatar, byte [] nickname, short gender, long time, byte [] busi_ext)
    {
        setType(type);
        setSub_type(sub_type);
        setReceiver(receiver);
        setContent(content);
        setAvatar(avatar);
        setNickname(nickname);
        setGender(gender);
        setTime(time);
        setBusi_ext(busi_ext);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        MsgInfo t = (MsgInfo) o;
        return (
            com.qq.taf.jce.JceUtil.equals(type, t.type) && 
            com.qq.taf.jce.JceUtil.equals(sub_type, t.sub_type) && 
            com.qq.taf.jce.JceUtil.equals(receiver, t.receiver) && 
            com.qq.taf.jce.JceUtil.equals(content, t.content) && 
            com.qq.taf.jce.JceUtil.equals(avatar, t.avatar) && 
            com.qq.taf.jce.JceUtil.equals(nickname, t.nickname) && 
            com.qq.taf.jce.JceUtil.equals(gender, t.gender) && 
            com.qq.taf.jce.JceUtil.equals(time, t.time) && 
            com.qq.taf.jce.JceUtil.equals(busi_ext, t.busi_ext) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(type, 0);
        _os.write(sub_type, 1);
        _os.write(receiver, 2);
        _os.write(content, 3);
        if (null != avatar)
        {
            _os.write(avatar, 4);
        }
        if (null != nickname)
        {
            _os.write(nickname, 5);
        }
        _os.write(gender, 6);
        _os.write(time, 7);
        if (null != busi_ext)
        {
            _os.write(busi_ext, 8);
        }
    }

    static int cache_type;
    static int cache_sub_type;
    static byte [] cache_content;
    static byte [] cache_nickname;
    static byte [] cache_busi_ext;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        setType((int) _is.read(type, 0, true));

        setSub_type((int) _is.read(sub_type, 1, true));

        setReceiver((long) _is.read(receiver, 2, true));

        if(null == cache_content)
        {
            cache_content = (byte[]) new byte[1];
            byte __var_1 = 0;
            ((byte[])cache_content)[0] = __var_1;
        }
        setContent((byte []) _is.read(cache_content, 3, true));

        setAvatar( _is.readString(4, false));

        if(null == cache_nickname)
        {
            cache_nickname = (byte[]) new byte[1];
            byte __var_2 = 0;
            ((byte[])cache_nickname)[0] = __var_2;
        }
        setNickname((byte []) _is.read(cache_nickname, 5, false));

        setGender((short) _is.read(gender, 6, false));

        setTime((long) _is.read(time, 7, false));

        if(null == cache_busi_ext)
        {
            cache_busi_ext = (byte[]) new byte[1];
            byte __var_3 = 0;
            ((byte[])cache_busi_ext)[0] = __var_3;
        }
        setBusi_ext((byte []) _is.read(cache_busi_ext, 8, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(type, "type");
        _ds.display(sub_type, "sub_type");
        _ds.display(receiver, "receiver");
        _ds.display(content, "content");
        _ds.display(avatar, "avatar");
        _ds.display(nickname, "nickname");
        _ds.display(gender, "gender");
        _ds.display(time, "time");
        _ds.display(busi_ext, "busi_ext");
    }

}

