// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.29 by WSRD Tencent.
// Generated from `chat.jce'
// **********************************************************************

package ld.Bu;

public final class MsgSubType implements java.io.Serializable
{
    private static MsgSubType[] __values = new MsgSubType[12];
    private int __value;
    private String __T = new String();

    public static final int _FROM_FRIREND = 1;
    public static final MsgSubType FROM_FRIREND = new MsgSubType(0,_FROM_FRIREND,"FROM_FRIREND");
    public static final int _FORM_GROUP = 2;
    public static final MsgSubType FORM_GROUP = new MsgSubType(1,_FORM_GROUP,"FORM_GROUP");
    public static final int _FEED_JOIN_GROUP = 3;
    public static final MsgSubType FEED_JOIN_GROUP = new MsgSubType(2,_FEED_JOIN_GROUP,"FEED_JOIN_GROUP");
    public static final int _FEED_ADD_FRIEND = 4;
    public static final MsgSubType FEED_ADD_FRIEND = new MsgSubType(3,_FEED_ADD_FRIEND,"FEED_ADD_FRIEND");
    public static final int _FEED_AGREE_FRIEND = 5;
    public static final MsgSubType FEED_AGREE_FRIEND = new MsgSubType(4,_FEED_AGREE_FRIEND,"FEED_AGREE_FRIEND");
    public static final int _FEED_REJECT_FRIEND = 6;
    public static final MsgSubType FEED_REJECT_FRIEND = new MsgSubType(5,_FEED_REJECT_FRIEND,"FEED_REJECT_FRIEND");
    public static final int _FEED_APPLY_GROUP = 7;
    public static final MsgSubType FEED_APPLY_GROUP = new MsgSubType(6,_FEED_APPLY_GROUP,"FEED_APPLY_GROUP");
    public static final int _FEED_REJECT_JOIN_GROUP = 8;
    public static final MsgSubType FEED_REJECT_JOIN_GROUP = new MsgSubType(7,_FEED_REJECT_JOIN_GROUP,"FEED_REJECT_JOIN_GROUP");
    public static final int _FEED_AGREE_JOIN_GROUP = 9;
    public static final MsgSubType FEED_AGREE_JOIN_GROUP = new MsgSubType(8,_FEED_AGREE_JOIN_GROUP,"FEED_AGREE_JOIN_GROUP");
    public static final int _FEED_INVITE_GROUP = 10;
    public static final MsgSubType FEED_INVITE_GROUP = new MsgSubType(9,_FEED_INVITE_GROUP,"FEED_INVITE_GROUP");
    public static final int _FEED_SYSTEM = 11;
    public static final MsgSubType FEED_SYSTEM = new MsgSubType(10,_FEED_SYSTEM,"FEED_SYSTEM");
    public static final int _FEED_OTHERS = 12;
    public static final MsgSubType FEED_OTHERS = new MsgSubType(11,_FEED_OTHERS,"FEED_OTHERS");

    public static MsgSubType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static MsgSubType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private MsgSubType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
