#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
defined('YII_CONF_LOCAL') or define('YII_CONF_LOCAL', false);

define('YII_ROOT', dirname(dirname(dirname(__DIR__))));

require(YII_ROOT . '/vendor/autoload.php');
require(YII_ROOT . '/vendor/yiisoft/yii2/Yii.php');

require(__DIR__ . '/config/bootstrap.php');

$config = require(__DIR__ . '/config/main.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
